//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountLedgerDetail
    {
        public int Id { get; set; }
        public int LedgerId { get; set; }
        public int HeadId { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string Narration { get; set; }
    
        public virtual AccountLedger AccountLedger { get; set; }
        public virtual COA COA { get; set; }
    }
}
