//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountRegister
    {
        public int Id { get; set; }
        public Nullable<int> HeadId { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> billdate { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> ChequeNo { get; set; }
        public string EntryType { get; set; }
        public Nullable<decimal> AnnualBudget { get; set; }
        public Nullable<decimal> BudgetRelease { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> IncomeTax { get; set; }
        public Nullable<decimal> SST { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> ManualTax { get; set; }
    
        public virtual COA COA { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
