//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BedManagement
    {
        public int ID { get; set; }
        public int BedID { get; set; }
        public int PatientID { get; set; }
        public Nullable<System.DateTime> AllotmentDate { get; set; }
        public string dischargeType { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Beds Beds { get; set; }
        public virtual Pateint Pateint { get; set; }
    }
}
