//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget_BK09OCT2019
    {
        public int Id { get; set; }
        public int HeadId { get; set; }
        public Nullable<int> Budget { get; set; }
        public Nullable<System.DateTime> budgetDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
