//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAllowance
    {
        public int Id { get; set; }
        public int EmpTypeId { get; set; }
        public Nullable<decimal> HouseRent { get; set; }
        public Nullable<decimal> Conveyance { get; set; }
        public Nullable<decimal> Casuality { get; set; }
        public Nullable<decimal> Entertaiment { get; set; }
        public Nullable<decimal> NonPracticing { get; set; }
        public Nullable<decimal> RCA { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public Nullable<decimal> Uniform { get; set; }
        public Nullable<decimal> Mess { get; set; }
        public Nullable<decimal> Nursing { get; set; }
        public Nullable<decimal> Health { get; set; }
        public Nullable<decimal> Institute { get; set; }
        public Nullable<decimal> Hardworking { get; set; }
        public Nullable<decimal> Orderly { get; set; }
        public Nullable<decimal> SeniorPost { get; set; }
        public Nullable<decimal> Washing { get; set; }
        public Nullable<decimal> Computer { get; set; }
        public Nullable<decimal> HPA { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
    }
}
