//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRNDetail
    {
        public int Id { get; set; }
        public int GRNID { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> rejectQty { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<System.DateTime> MgfDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string batchno { get; set; }
        public Nullable<int> lowQuantity { get; set; }
    
        public virtual GRN GRN { get; set; }
        public virtual Product Product { get; set; }
    }
}
