//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryIssuanceDetail
    {
        public int Id { get; set; }
        public Nullable<int> VoucherNo { get; set; }
        public Nullable<int> MainStoreId { get; set; }
        public Nullable<int> MainCategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> IssuanceQty { get; set; }
        public Nullable<int> BalanceQty { get; set; }
        public Nullable<int> IssuanceId { get; set; }
    }
}
