//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IRDetails
    {
        public int Id { get; set; }
        public int IRID { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> StockQty { get; set; }
        public Nullable<int> ReqQty { get; set; }
        public Nullable<int> DelvQty { get; set; }
        public string batchno { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public string Suppliment { get; set; }
    
        public virtual IR IR { get; set; }
        public virtual Products Products { get; set; }
    }
}
