//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_List
    {
        public int menuID { get; set; }
        public Nullable<int> menuParentID { get; set; }
        public string menuName { get; set; }
        public string controllerName { get; set; }
        public string actionName { get; set; }
        public string applicationPath { get; set; }
    }
}
