//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuAuthorization
    {
        public int authorizationID { get; set; }
        public Nullable<int> employeeID { get; set; }
        public Nullable<int> designationID { get; set; }
        public Nullable<int> appCompanyMapID { get; set; }
        public Nullable<bool> isDashboard { get; set; }
        public string imageURL { get; set; }
    }
}
