//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLCDetail
    {
        public int Id { get; set; }
        public int MLCId { get; set; }
        public string InjuryNo { get; set; }
        public string InjuryNature { get; set; }
        public string Weapon { get; set; }
        public string Duration { get; set; }
    
        public virtual MLC MLC { get; set; }
    }
}
