//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pateint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pateint()
        {
            this.BedManagement = new HashSet<BedManagement>();
            this.LabRegistration = new HashSet<LabRegistration>();
            this.LabTest = new HashSet<LabTest>();
            this.PateintAppointments = new HashSet<PateintAppointments>();
            this.SemanAnalysis = new HashSet<SemanAnalysis>();
            this.TestResult = new HashSet<TestResult>();
        }
    
        public int Id { get; set; }
        public string NIC { get; set; }
        public string NICType { get; set; }
        public int PatientTypeID { get; set; }
        public string MRNo { get; set; }
        public string Name { get; set; }
        public string FName { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public string BloodGroup { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public Nullable<System.DateTime> AdmitDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> employeeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BedManagement> BedManagement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabRegistration> LabRegistration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabTest> LabTest { get; set; }
        public virtual PatientType PatientType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PateintAppointments> PateintAppointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SemanAnalysis> SemanAnalysis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestResult> TestResult { get; set; }
    }
}
