//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientPrescriptions
    {
        public int Id { get; set; }
        public int PatientRecordId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual PateintAppointments PateintAppointments { get; set; }
        public virtual Products Products { get; set; }
    }
}
