//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pharmacy
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public Nullable<System.DateTime> recievedDate { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public Nullable<int> QtyRec { get; set; }
        public Nullable<int> QtyIssue { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
