//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    
    public partial class Report_CashBook_Result1
    {
        public string HeadName { get; set; }
        public string Code { get; set; }
        public string billno { get; set; }
        public Nullable<System.DateTime> billdate { get; set; }
        public string partyName { get; set; }
        public Nullable<decimal> BudgetRelease { get; set; }
        public Nullable<decimal> TaxDeduction { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> openingBal { get; set; }
        public Nullable<decimal> closingBal { get; set; }
    }
}
