//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCLHMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Id { get; set; }
        public int RefId { get; set; }
        public string RefCode { get; set; }
        public int ProductId { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
        public string batchno { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> QtyIn { get; set; }
        public Nullable<int> QtyOut { get; set; }
        public string IssuedTo { get; set; }
        public string tranType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual GRN GRN { get; set; }
        public virtual IR IR { get; set; }
        public virtual Products Products { get; set; }
    }
}
